### ISSUE TITLE
Link Broken for Copilot Token Extraction?

### ISSUE THREAD

**Issue by MatMice** [minosvasilias/godot-copilot#12]
I am not sure how to get my Token for copilot... the link is broken :/

**Comment by minosvasilias** [comment]
Yeah, the repo originally implementing Copilot token usage was nuked.
I feel like this project is already somewhat at risk of the same happening since i added support for copilot tokens, so i'm hesitant to include more details myself. But the originally linked repo still exists on [gitlab](https://gitlab.com/aaamoon/copilot-gpt4-service?tab=readme-ov-file#obtaining-copilot-token).

**Comment by minosvasilias** [comment]
Also updated in https://github.com/minosvasilias/godot-copilot/pull/13.
